Repository Kernel360/KDEV4-SODA-BE, pull requests merged in 2025-05, with the labels that each got.

#286 [Refactor] Project 패키지 DDD Layer에 맞게 재분류
  src/main/java/com/soda/global/init/TestDataLoader.java
  src/main/java/com/soda/global/log/data/aspect/EntityLogAspect.java
  src/main/java/com/soda/project/application/event/ProjectEventListener.java
  src/main/java/com/soda/project/application/stats/ProjectStatsUpdateService.java
  src/main/java/com/soda/project/domain/ProjectService.java
  src/main/java/com/soda/project/domain/company/CompanyProject.java
  src/main/java/com/soda/project/domain/company/CompanyProjectService.java
  src/main/java/com/soda/project/domain/company/dto/CompanyProjectDTO.java
  src/main/java/com/soda/project/domain/company/enums/CompanyProjectRole.java
  src/main/java/com/soda/project/domain/dto/ProjectDTO.java
  src/main/java/com/soda/project/domain/event/ProjectCreatedEvent.java
  src/main/java/com/soda/project/domain/member/MemberProject.java
  src/main/java/com/soda/project/domain/member/MemberProjectService.java
  src/main/java/com/soda/project/domain/member/dto/MemberProjectDTO.java
  src/main/java/com/soda/project/domain/member/enums/MemberProjectRole.java
  src/main/java/com/soda/project/domain/stage/article/ArticleService.java
  src/main/java/com/soda/project/domain/stage/request/RequestService.java
  src/main/java/com/soda/project/domain/stage/request/response/ResponseService.java
  src/main/java/com/soda/project/domain/stats/ProjectDailyStats.java
  src/main/java/com/soda/project/infrastructure/CompanyProjectRepository.java
  src/main/java/com/soda/project/infrastructure/MemberProjectRepository.java
  src/main/java/com/soda/project/infrastructure/MemberProjectRepositoryCustom.java
  src/main/java/com/soda/project/infrastructure/MemberProjectRepositoryImpl.java
  src/main/java/com/soda/project/infrastructure/ProjectDailyStatsRepository.java
  src/main/java/com/soda/project/infrastructure/ProjectDailyStatsRepositoryCustom.java
  src/main/java/com/soda/project/infrastructure/ProjectDailyStatsRepositoryImpl.java
  src/main/java/com/soda/project/interfaces/dto/DevCompanyAssignmentResponse.java
  src/main/java/com/soda/project/interfaces/dto/MyProjectListResponse.java
  src/main/java/com/soda/project/interfaces/dto/ProjectCompanyAddRequest.java
  src/main/java/com/soda/project/interfaces/dto/ProjectCompanyAddResponse.java
  src/main/java/com/soda/project/interfaces/dto/ProjectCreateResponse.java
  src/main/java/com/soda/project/interfaces/dto/ProjectMemberResponse.java
  src/main/java/com/soda/project/interfaces/dto/ProjectMemberSearchCondition.java
Labels: 🔧 Refactor

#285 [Refact] Response(Approve) 생성 과정 레이어별로 책임 분리
  src/main/java/com/soda/member/service/MemberService.java
  src/main/java/com/soda/project/application/stage/request/response/ResponseFacade.java
  src/main/java/com/soda/project/application/stage/request/validator/RequestApproverValidator.java
  src/main/java/com/soda/project/application/validator/ProjectValidator.java
  src/main/java/com/soda/project/domain/stage/request/Request.java
  src/main/java/com/soda/project/domain/stage/request/RequestService.java
  src/main/java/com/soda/project/domain/stage/request/response/Response.java
  src/main/java/com/soda/project/domain/stage/request/response/ResponseFactory.java
  src/main/java/com/soda/project/domain/stage/request/response/ResponseService.java
  src/main/java/com/soda/project/interfaces/ResponseController.java
Labels: 🔧 Refactor

#287 [Refact] Response (C)RUD DDD OOP 리팩토링
  src/main/java/com/soda/project/application/stage/request/response/ResponseFacade.java
  src/main/java/com/soda/project/application/stage/request/response/validator/ResponseValidator.java
  src/main/java/com/soda/project/domain/stage/request/response/Response.java
  src/main/java/com/soda/project/domain/stage/request/response/ResponseFactory.java
  src/main/java/com/soda/project/domain/stage/request/response/ResponseProvider.java
  src/main/java/com/soda/project/domain/stage/request/response/ResponseService.java
  src/main/java/com/soda/project/infrastructure/ResponseProviderImpl.java
  src/main/java/com/soda/project/interfaces/ResponseController.java
Labels: 🔧 Refactor

#292 [Fix] ProviderImpl에 Repository 빈 주입(final을 빼먹었었음)
  src/main/java/com/soda/project/infrastructure/ResponseProviderImpl.java
Labels: 🐞 Bugfix

#300 [Refactor] Project CRUD DDD/OOP 리팩토링
  src/main/java/com/soda/member/domain/CompanyService.java
  src/main/java/com/soda/member/domain/MemberService.java
  src/main/java/com/soda/member/infrastructure/CompanyRepository.java
  src/main/java/com/soda/project/application/ProjectFacade.java
  src/main/java/com/soda/project/application/ProjectResponseBuilder.java
  src/main/java/com/soda/project/application/stage/article/vote/validator/VoteValidator.java
  src/main/java/com/soda/project/application/validator/ProjectValidator.java
  src/main/java/com/soda/project/domain/Project.java
  src/main/java/com/soda/project/domain/ProjectProvider.java
  src/main/java/com/soda/project/domain/ProjectService.java
  src/main/java/com/soda/project/domain/company/CompanyProject.java
  src/main/java/com/soda/project/domain/company/CompanyProjectProvider.java
  src/main/java/com/soda/project/domain/company/CompanyProjectRole.java
  src/main/java/com/soda/project/domain/company/CompanyProjectService.java
  src/main/java/com/soda/project/domain/member/MemberProject.java
  src/main/java/com/soda/project/domain/member/MemberProjectProvider.java
  src/main/java/com/soda/project/domain/member/MemberProjectRole.java
  src/main/java/com/soda/project/domain/member/MemberProjectService.java
  src/main/java/com/soda/project/domain/stage/Stage.java
  src/main/java/com/soda/project/domain/stats/ProjectStatsProvider.java
  src/main/java/com/soda/project/domain/stats/ProjectStatsService.java
  src/main/java/com/soda/project/infrastructure/CompanyProjectProviderImpl.java
  src/main/java/com/soda/project/infrastructure/CompanyProjectRepository.java
  src/main/java/com/soda/project/infrastructure/MemberProjectProviderImpl.java
  src/main/java/com/soda/project/infrastructure/MemberProjectRepository.java
  src/main/java/com/soda/project/infrastructure/MemberProjectRepositoryCustom.java
  src/main/java/com/soda/project/infrastructure/MemberProjectRepositoryImpl.java
  src/main/java/com/soda/project/infrastructure/ProjectProviderImpl.java
  src/main/java/com/soda/project/infrastructure/ProjectStatsProviderImpl.java
  src/main/java/com/soda/project/interfaces/ProjectController.java
  src/main/java/com/soda/project/interfaces/dto/DevCompanyAssignmentResponse.java
  src/main/java/com/soda/project/interfaces/dto/MyProjectListResponse.java
  src/main/java/com/soda/project/interfaces/dto/ProjectCompanyAddRequest.java
  src/main/java/com/soda/project/interfaces/dto/ProjectCompanyAddResponse.java
  src/main/java/com/soda/project/interfaces/dto/ProjectCreateResponse.java
  src/main/java/com/soda/project/interfaces/dto/ProjectMemberResponse.java
  src/main/java/com/soda/project/interfaces/dto/ProjectMemberSearchCondition.java
  src/main/java/com/soda/project/interfaces/dto/company/CompanyProjectDTO.java
  src/main/java/com/soda/project/interfaces/dto/member/MemberProjectDTO.java
Labels: 🔧 Refactor

#302 [Refactor] Company CRUD DDD/OOP 리팩토링
  src/main/java/com/soda/global/init/InitialDataLoader.java
  src/main/java/com/soda/global/init/TestDataLoader.java
  src/main/java/com/soda/global/log/data/aspect/EntityLogAspect.java
  src/main/java/com/soda/member/application/CompanyFacade.java
  src/main/java/com/soda/member/domain/AdminMemberService.java
  src/main/java/com/soda/member/domain/AuthService.java
  src/main/java/com/soda/member/domain/Company.java
  src/main/java/com/soda/member/domain/CompanyService.java
  src/main/java/com/soda/member/domain/Member.java
  src/main/java/com/soda/member/domain/MemberService.java
  src/main/java/com/soda/member/domain/company/Company.java
  src/main/java/com/soda/member/domain/company/CompanyErrorCode.java
  src/main/java/com/soda/member/domain/company/CompanyProvider.java
  src/main/java/com/soda/member/domain/company/CompanyService.java
  src/main/java/com/soda/member/domain/company/CompanyStatsService.java
  src/main/java/com/soda/member/domain/company/StatisticsUnit.java
  src/main/java/com/soda/member/infrastructure/CompanyProviderImpl.java
  src/main/java/com/soda/member/infrastructure/CompanyRepository.java
  src/main/java/com/soda/member/infrastructure/CompanyRepositoryImpl.java
  src/main/java/com/soda/member/interfaces/CompanyController.java
  src/main/java/com/soda/member/interfaces/dto/CompanyCreationStatRaw.java
  src/main/java/com/soda/member/interfaces/dto/company/CompanyCreateRequest.java
  src/main/java/com/soda/member/interfaces/dto/company/CompanyResponse.java
  src/main/java/com/soda/member/interfaces/dto/company/CompanyTrendSearchCondition.java
  src/main/java/com/soda/member/interfaces/dto/company/CompanyUpdateRequest.java
  src/main/java/com/soda/project/application/ProjectFacade.java
  src/main/java/com/soda/project/application/ProjectResponseBuilder.java
  src/main/java/com/soda/project/application/stage/article/vote/validator/VoteValidator.java
  src/main/java/com/soda/project/application/validator/ProjectValidator.java
  src/main/java/com/soda/project/domain/Project.java
  src/main/java/com/soda/project/domain/ProjectService.java
  src/main/java/com/soda/project/domain/company/CompanyProject.java
  src/main/java/com/soda/project/domain/company/CompanyProjectProvider.java
  src/main/java/com/soda/project/domain/company/CompanyProjectService.java
  src/main/java/com/soda/project/domain/member/MemberProjectProvider.java
  src/main/java/com/soda/project/domain/member/MemberProjectService.java
  src/main/java/com/soda/project/infrastructure/CompanyProjectProviderImpl.java
  src/main/java/com/soda/project/infrastructure/CompanyProjectRepository.java
  src/main/java/com/soda/project/infrastructure/MemberProjectProviderImpl.java
  src/main/java/com/soda/project/infrastructure/MemberProjectRepository.java
  src/main/java/com/soda/project/infrastructure/MemberProjectRepositoryImpl.java
  src/main/java/com/soda/project/infrastructure/stage/article/ArticleRepositoryImpl.java
  src/main/java/com/soda/project/interfaces/dto/ProjectCompanyAddResponse.java
  src/main/java/com/soda/project/interfaces/dto/ProjectCreateResponse.java
  src/main/java/com/soda/project/interfaces/dto/ProjectMemberResponse.java
  src/main/java/com/soda/project/interfaces/dto/company/CompanyProjectDTO.java
Labels: 🔧 Refactor

#309 [Fix] 프로젝트 생성 시 상태 null 인 오류 해결
  src/main/java/com/soda/project/domain/Project.java
Labels: 🐞 Bugfix

#311 [fix] 개발사 추가 오류 해결
  src/main/java/com/soda/project/application/ProjectFacade.java
Labels: 🐞 Bugfix

#315 [Fix] 로깅 엔티티액션 UPDATE_STATUS인 메서드 UPDATE로 변경
  src/main/java/com/soda/project/application/ProjectFacade.java
Labels: 🐞 Bugfix

#317 [Fix] vote 생성 오류 해결
  src/main/java/com/soda/project/domain/stage/article/vote/VoteFactory.java
  src/main/java/com/soda/project/domain/stage/article/vote/VoteService.java
Labels: 🐞 Bugfix

#322 [Docs] README 작성
  README.md
Labels: 📃 Docs

#313 [Refactor] Stage CRUD DDD/OOP 리팩토링
  src/main/java/com/soda/project/application/stage/StageFacade.java
  src/main/java/com/soda/project/application/stage/validator/StageValidator.java
  src/main/java/com/soda/project/domain/ProjectProvider.java
  src/main/java/com/soda/project/domain/stage/Stage.java
  src/main/java/com/soda/project/domain/stage/StageConstants.java
  src/main/java/com/soda/project/domain/stage/StageErrorCode.java
  src/main/java/com/soda/project/domain/stage/StageProvider.java
  src/main/java/com/soda/project/domain/stage/StageService.java
  src/main/java/com/soda/project/infrastructure/ProjectProviderImpl.java
  src/main/java/com/soda/project/infrastructure/stage/StageProviderImpl.java
  src/main/java/com/soda/project/infrastructure/stage/StageValidatorImpl.java
  src/main/java/com/soda/project/interfaces/stage/StageController.java
  src/main/java/com/soda/project/interfaces/stage/dto/StageCreateRequest.java
  src/main/java/com/soda/project/interfaces/stage/dto/StageUpdateRequest.java
Labels: 🔧 Refactor

#325 [Fix] 개발사 및 어드민이 승인요청 생성/수정/삭제 되지않는 버그 해결
  src/main/java/com/soda/project/application/stage/request/RequestFacade.java
  src/main/java/com/soda/project/application/stage/request/RequestValidator.java
  src/main/java/com/soda/project/application/stage/request/response/ResponseFacade.java
  src/main/java/com/soda/project/application/validator/ProjectValidator.java
Labels: 🐞 Bugfix

#327 [Fix] 재승인요청 생성시 validate가 비정상적으로 되는 오류 해결
  src/main/java/com/soda/project/application/stage/request/RequestFacade.java
Labels: 🐞 Bugfix

#329 [Fix] 게시글 수정 시 단계 수정 안되는 버그 해결
  src/main/java/com/soda/project/application/stage/article/ArticleFacade.java
  src/main/java/com/soda/project/domain/stage/StageService.java
  src/main/java/com/soda/project/domain/stage/article/Article.java
  src/main/java/com/soda/project/domain/stage/article/ArticleService.java
Labels: 🐞 Bugfix

#331 [Feat] presignedUrl발급 시 ACL 퍼블릭읽기 설정 추가
  src/main/java/com/soda/project/domain/stage/common/file/S3Service.java
Labels: 🐞 Bugfix

#332 Revert "[Feat] presignedUrl발급 시 ACL 퍼블릭읽기 설정 추가"
  src/main/java/com/soda/project/domain/stage/common/file/S3Service.java
Labels: 🐞 Bugfix

#333 [Fix] 파일url에 uuid까지 반환되게 수정
  src/main/java/com/soda/project/domain/stage/common/file/FileFactory.java
  src/main/java/com/soda/project/domain/stage/common/file/PresignedUrlWithKey.java
  src/main/java/com/soda/project/domain/stage/common/file/S3Service.java
Labels: 🐞 Bugfix

#334 [Fix] 파일 메타정보 DB에 저장 할 때 uploads/{uuid}_는 저장되지 않게 수정
  src/main/java/com/soda/project/domain/stage/common/file/FileFactory.java
Labels: 🐞 Bugfix

#342 [Feature] 로드밸런서 헬스체크용 액츄에이터 추가
  build.gradle
  src/main/resources/application.yml
Labels: 🎤 Perform
