Repository Kernel360/KDEV4-SODA-BE, pull requests merged in 2025-03, with the labels that each got.

#6 [CI/CD] 백엔드 CICD 구축
  README.md
Labels: 🤖 CI/CD

#9 [Feature] 프로젝트 기능
  src/main/java/com/soda/common/BaseEntity.java
  src/main/java/com/soda/global/response/ErrorCode.java
  src/main/java/com/soda/member/repository/CompanyRepository.java
  src/main/java/com/soda/member/repository/MemberRepository.java
  src/main/java/com/soda/project/controller/ProjectController.java
  src/main/java/com/soda/project/domain/CompanyProjectDTO.java
  src/main/java/com/soda/project/domain/MemberProjectDTO.java
  src/main/java/com/soda/project/domain/ProjectCreateRequest.java
  src/main/java/com/soda/project/domain/ProjectCreateResponse.java
  src/main/java/com/soda/project/domain/ProjectDTO.java
  src/main/java/com/soda/project/domain/ProjectListResponse.java
  src/main/java/com/soda/project/domain/ProjectResponse.java
  src/main/java/com/soda/project/entity/CompanyProject.java
  src/main/java/com/soda/project/entity/MemberProject.java
  src/main/java/com/soda/project/entity/Project.java
  src/main/java/com/soda/project/repository/CompanyProjectRepository.java
  src/main/java/com/soda/project/repository/MemberProjectRepository.java
  src/main/java/com/soda/project/repository/ProjectRepository.java
  src/main/java/com/soda/project/service/ProjectService.java
Labels: ✨ Feature

#15 [Feature] 승인요청(Request) CRUD 구현 및 리팩토링
  src/main/java/com/soda/common/BaseEntity.java
  src/main/java/com/soda/global/config/InitialDataLoader.java
  src/main/java/com/soda/global/config/SwaggerConfig.java
  src/main/java/com/soda/global/config/TestDataLoader.java
  src/main/java/com/soda/global/response/ErrorCode.java
  src/main/java/com/soda/global/security/auth/UserDetailsServiceImpl.java
  src/main/java/com/soda/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/soda/member/entity/Member.java
  src/main/java/com/soda/member/repository/MemberRepository.java
  src/main/java/com/soda/project/entity/Stage.java
  src/main/java/com/soda/project/entity/Task.java
  src/main/java/com/soda/project/repository/StageRepository.java
  src/main/java/com/soda/project/repository/TaskRepository.java
  src/main/java/com/soda/request/controller/ReqeustController.java
  src/main/java/com/soda/request/dto/RequestCreateRequest.java
  src/main/java/com/soda/request/dto/RequestCreateResponse.java
  src/main/java/com/soda/request/dto/RequestDTO.java
  src/main/java/com/soda/request/dto/RequestDeleteResponse.java
  src/main/java/com/soda/request/dto/RequestUpdateRequest.java
  src/main/java/com/soda/request/dto/RequestUpdateResponse.java
  src/main/java/com/soda/request/entity/Request.java
  src/main/java/com/soda/request/enums/RequestStatus.java
  src/main/java/com/soda/request/repository/RequestRepository.java
  src/main/java/com/soda/request/service/RequestService.java
  src/main/resources/application.yml
  src/test/java/com/soda/request/service/RequestServiceTest.java
Labels: ✨ Feature

#19 fix: 데이터 수정시에도 createdAt이 업데이트 되는 버그 해결
  src/main/java/com/soda/common/BaseEntity.java
  src/main/java/com/soda/request/service/RequestService.java
Labels: 🐞 Bugfix

#17 [Refactor] refreshToken 저장 위치, 응답 방식 변경
  src/main/java/com/soda/global/config/InitialDataLoader.java
  src/main/java/com/soda/global/config/TestDataLoader.java
  src/main/java/com/soda/global/security/auth/UserDetailsImpl.java
  src/main/java/com/soda/global/security/auth/UserDetailsServiceImpl.java
  src/main/java/com/soda/global/security/config/SecurityConfig.java
  src/main/java/com/soda/member/controller/AuthController.java
  src/main/java/com/soda/member/dto/LoginResponse.java
  src/main/java/com/soda/member/entity/Member.java
  src/main/java/com/soda/member/entity/RefreshToken.java
  src/main/java/com/soda/member/repository/RefreshTokenRepository.java
  src/main/java/com/soda/member/service/AuthService.java
Labels: 🔧 Refactor

#32 [Refactor] updatedAt 원하는 필드 변경시에만 변경되게 리팩토링
  src/main/java/com/soda/common/BaseEntity.java
  src/main/java/com/soda/common/CustomAuditingEntityListener.java
  src/main/java/com/soda/common/TrackUpdate.java
  src/main/java/com/soda/request/entity/Request.java
Labels: 🔧 Refactor

#33 [Refactor] 게시글 관련 일부 API 리팩토링
  src/main/java/com/soda/article/controller/ArticleController.java
  src/main/java/com/soda/article/domain/ArticleModifyRequest.java
  src/main/java/com/soda/article/domain/ArticleModifyResponse.java
  src/main/java/com/soda/article/error/ArticleErrorCode.java
  src/main/java/com/soda/article/repository/ArticleRepository.java
  src/main/java/com/soda/article/service/ArticleService.java
  src/main/java/com/soda/global/response/CommonErrorCode.java
  src/main/java/com/soda/global/response/ErrorCode.java
  src/main/java/com/soda/global/response/GeneralException.java
  src/main/java/com/soda/global/security/auth/UserDetailsServiceImpl.java
  src/main/java/com/soda/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/soda/member/service/AuthService.java
  src/main/java/com/soda/project/error/ProjectErrorCode.java
  src/main/java/com/soda/project/service/ProjectService.java
  src/main/java/com/soda/request/service/RequestService.java
Labels: 🔧 Refactor

#46 [Feature] 게시글 댓글 기능
  src/main/java/com/soda/article/controller/ArticleController.java
  src/main/java/com/soda/article/controller/CommentController.java
  src/main/java/com/soda/article/domain/CommentCreateRequest.java
  src/main/java/com/soda/article/domain/CommentCreateResponse.java
  src/main/java/com/soda/article/domain/CommentDTO.java
  src/main/java/com/soda/article/domain/CommentUpdateRequest.java
  src/main/java/com/soda/article/domain/CommentUpdateResponse.java
  src/main/java/com/soda/article/entity/Comment.java
  src/main/java/com/soda/article/error/CommentErrorCode.java
  src/main/java/com/soda/article/repository/CommentRepository.java
  src/main/java/com/soda/article/service/ArticleService.java
  src/main/java/com/soda/article/service/CommentService.java
Labels: ✨ Feature

#48 [Refactor] 게시글/댓글 코드리뷰 기반 리팩토링
  src/main/java/com/soda/article/controller/ArticleController.java
  src/main/java/com/soda/article/controller/CommentController.java
  src/main/java/com/soda/article/domain/CommentCreateResponse.java
  src/main/java/com/soda/article/domain/CommentUpdateRequest.java
  src/main/java/com/soda/article/domain/CommentUpdateResponse.java
  src/main/java/com/soda/article/domain/article/ArticleDTO.java
  src/main/java/com/soda/article/domain/article/ArticleFileDTO.java
  src/main/java/com/soda/article/domain/article/ArticleLinkDTO.java
  src/main/java/com/soda/article/domain/article/ArticleModifyRequest.java
  src/main/java/com/soda/article/domain/article/ArticleModifyResponse.java
  src/main/java/com/soda/article/domain/article/ArticleViewResponse.java
  src/main/java/com/soda/article/domain/comment/CommentCreateRequest.java
  src/main/java/com/soda/article/domain/comment/CommentCreateResponse.java
  src/main/java/com/soda/article/domain/comment/CommentDTO.java
  src/main/java/com/soda/article/domain/comment/CommentUpdateRequest.java
  src/main/java/com/soda/article/domain/comment/CommentUpdateResponse.java
  src/main/java/com/soda/article/entity/Comment.java
  src/main/java/com/soda/article/error/ArticleErrorCode.java
  src/main/java/com/soda/article/error/CommentErrorCode.java
  src/main/java/com/soda/article/service/ArticleService.java
  src/main/java/com/soda/article/service/CommentService.java
  src/main/java/com/soda/request/dto/response/ResponseDTO.java
Labels: 🔧 Refactor

#54 [Feature] 파일 업로드/삭제 기능 구현 및 파일 책임 분리
  build.gradle
  src/main/java/com/soda/common/file/dto/FileDTO.java
  src/main/java/com/soda/common/file/dto/FileDeleteResponse.java
  src/main/java/com/soda/common/file/dto/FileUploadResponse.java
  src/main/java/com/soda/common/file/error/FileErrorCode.java
  src/main/java/com/soda/common/file/model/FileBase.java
  src/main/java/com/soda/common/file/service/FileService.java
  src/main/java/com/soda/common/file/service/S3Service.java
  src/main/java/com/soda/common/file/strategy/FileStrategy.java
  src/main/java/com/soda/common/link/dto/LinkDTO.java
  src/main/java/com/soda/common/link/model/LinkBase.java
  src/main/java/com/soda/global/config/AWSConfig.java
  src/main/java/com/soda/global/init/InitialDataLoader.java
  src/main/java/com/soda/global/init/TestDataLoader.java
  src/main/java/com/soda/global/response/CommonErrorCode.java
  src/main/java/com/soda/request/controller/RequestController.java
  src/main/java/com/soda/request/controller/ResponseController.java
  src/main/java/com/soda/request/dto/request/RequestCreateRequest.java
  src/main/java/com/soda/request/dto/request/RequestCreateResponse.java
  src/main/java/com/soda/request/dto/request/RequestDTO.java
  src/main/java/com/soda/request/dto/request/RequestUpdateRequest.java
  src/main/java/com/soda/request/dto/request/RequestUpdateResponse.java
  src/main/java/com/soda/request/dto/response/RequestApproveRequest.java
  src/main/java/com/soda/request/dto/response/RequestApproveResponse.java
  src/main/java/com/soda/request/dto/response/RequestRejectRequest.java
  src/main/java/com/soda/request/dto/response/RequestRejectResponse.java
  src/main/java/com/soda/request/dto/response/ResponseDTO.java
  src/main/java/com/soda/request/dto/response/ResponseUpdateResponse.java
  src/main/java/com/soda/request/entity/Request.java
  src/main/java/com/soda/request/entity/RequestFile.java
  src/main/java/com/soda/request/entity/RequestLink.java
  src/main/java/com/soda/request/entity/Response.java
  src/main/java/com/soda/request/entity/ResponseFile.java
  src/main/java/com/soda/request/entity/ResponseLink.java
  src/main/java/com/soda/request/error/RequestErrorCode.java
  src/main/java/com/soda/request/error/ResponseErrorCode.java
  src/main/java/com/soda/request/repository/RequestFileRepository.java
  src/main/java/com/soda/request/repository/ResponseFileRepository.java
  src/main/java/com/soda/request/service/RequestFileStrategy.java
  src/main/java/com/soda/request/service/RequestService.java
  src/main/java/com/soda/request/service/ResponseFileStrategy.java
  src/main/java/com/soda/request/service/ResponseService.java
  src/main/resources/application.yml
Labels: ✨ Feature

#60 [Refactor] Project Service 리팩토링
  src/main/java/com/soda/member/service/CompanyService.java
  src/main/java/com/soda/member/service/MemberService.java
  src/main/java/com/soda/project/service/CompanyProjectService.java
  src/main/java/com/soda/project/service/MemberProjectService.java
  src/main/java/com/soda/project/service/ProjectService.java
Labels: 🔧 Refactor

#62 [hotfix] 순환참조 에러 해결
  src/main/java/com/soda/project/service/CompanyProjectService.java
  src/main/java/com/soda/project/service/ProjectService.java
Labels: 🐞 Bugfix

#67 [hotfix] stage 오류 해결
  src/main/java/com/soda/article/service/ArticleService.java
  src/main/java/com/soda/project/service/StageService.java
Labels: 🐞 Bugfix
