Repository Kernel360/KDEV4-SODA-BE, pull requests merged in 2025-04, with the labels that each got.

#70 [Refactor] Article service code 리팩토링
  src/main/java/com/soda/member/service/MemberService.java
  src/main/java/com/soda/project/repository/MemberProjectRepository.java
  src/main/java/com/soda/project/service/CompanyProjectService.java
  src/main/java/com/soda/project/service/MemberProjectService.java
  src/main/java/com/soda/project/service/ProjectService.java
Labels: 🔧 Refactor

#71 [Refactor] Member, Company 리팩토링
  src/main/java/com/soda/member/dto/MemberUpdateRequest.java
  src/main/java/com/soda/member/dto/SignupRequest.java
  src/main/java/com/soda/member/entity/Member.java
  src/main/java/com/soda/member/error/AuthErrorCode.java
  src/main/java/com/soda/member/repository/CompanyRepository.java
  src/main/java/com/soda/member/repository/MemberRepository.java
  src/main/java/com/soda/member/service/AuthService.java
  src/main/java/com/soda/member/service/CompanyService.java
  src/main/java/com/soda/member/service/MemberService.java
  src/main/java/com/soda/project/service/StageService.java
  src/main/java/com/soda/project/service/TaskService.java
Labels: 🔧 Refactor

#73 [Refactor] Article, Comment 관련 코드 리팩토링
  src/main/java/com/soda/article/domain/article/ArticleCreateRequest.java
  src/main/java/com/soda/article/service/ArticleFileService.java
  src/main/java/com/soda/article/service/ArticleLinkService.java
  src/main/java/com/soda/article/service/ArticleService.java
  src/main/java/com/soda/article/service/CommentService.java
  src/main/java/com/soda/member/error/MemberErrorCode.java
  src/main/java/com/soda/project/service/StageService.java
Labels: 🔧 Refactor

#75 [Refact] 파일 업로드 분리
  src/main/java/com/soda/article/domain/article/ArticleCreateRequest.java
  src/main/java/com/soda/article/domain/article/ArticleModifyRequest.java
  src/main/java/com/soda/article/service/ArticleService.java
  src/main/java/com/soda/member/dto/LoginRequest.java
  src/main/java/com/soda/request/controller/RequestController.java
  src/main/java/com/soda/request/controller/ResponseController.java
  src/main/java/com/soda/request/dto/response/RequestApproveRequest.java
  src/main/java/com/soda/request/dto/response/RequestRejectRequest.java
  src/main/java/com/soda/request/dto/response/ResponseUpdateRequest.java
  src/main/java/com/soda/request/entity/Response.java
  src/main/java/com/soda/request/entity/ResponseFile.java
  src/main/java/com/soda/request/service/RequestService.java
  src/main/java/com/soda/request/service/ResponseService.java
  src/main/java/com/soda/request/strategy/ResponseFileStrategy.java
  src/main/java/com/soda/request/strategy/ResponseLinkStrategy.java
Labels: 🔧 Refactor

#77 🚧 [Refact] Article에 Link/File 전략패턴 적용 및 생성/수정시 링크 다중 삽입 가능하게 적용
  src/main/java/com/soda/article/domain/article/ArticleCreateRequest.java
  src/main/java/com/soda/article/domain/article/ArticleModifyRequest.java
  src/main/java/com/soda/article/entity/Article.java
  src/main/java/com/soda/article/entity/ArticleFile.java
  src/main/java/com/soda/article/entity/ArticleLink.java
  src/main/java/com/soda/article/service/ArticleLinkService.java
  src/main/java/com/soda/article/service/ArticleService.java
  src/main/java/com/soda/article/strategy/ArticleFileStrategy.java
  src/main/java/com/soda/article/strategy/ArticleLinkStrategy.java
Labels: 🔧 Refactor

#79 [Feature] 몽고DB 연결
  build.gradle
  src/main/java/com/soda/SodaApplication.java
  src/main/java/com/soda/global/log/LogController.java
  src/main/java/com/soda/global/log/LogInfo.java
  src/main/java/com/soda/global/log/LogRepository.java
  src/main/java/com/soda/global/log/LogService.java
  src/main/resources/application.yml
Labels: ✨ Feature

#81 [fix] 게시글 관련 유효성 검사 로직 수정
  src/main/java/com/soda/article/service/ArticleService.java
Labels: 🐞 Bugfix

#86 [fix] 조회 시 id 없는 버그 해결
  src/main/java/com/soda/project/domain/ProjectListResponse.java
  src/main/java/com/soda/project/domain/ProjectResponse.java
  src/main/java/com/soda/project/service/ProjectService.java
Labels: 🐞 Bugfix

#91 [Fix] Article, Comment API 연동 시 오류 해결
  src/main/java/com/soda/article/domain/article/ArticleCreateResponse.java
  src/main/java/com/soda/article/domain/article/ArticleViewResponse.java
  src/main/java/com/soda/article/domain/comment/CommentDTO.java
  src/main/java/com/soda/article/repository/CommentRepository.java
  src/main/java/com/soda/article/service/CommentService.java
Labels: 🐞 Bugfix

#97 [Fix] 몽고DB ssl연결 옵션 추가
  src/main/resources/application.yml
Labels: 🐞 Bugfix

#102 [Feature] 사용자 참여 중 전체 프로젝트 조회 기능 추가
  src/main/java/com/soda/project/controller/ProjectController.java
  src/main/java/com/soda/project/repository/MemberProjectRepository.java
  src/main/java/com/soda/project/repository/ProjectRepository.java
  src/main/java/com/soda/project/service/MemberProjectService.java
  src/main/java/com/soda/project/service/ProjectService.java
Labels: ✨ Feature

#106 [Fix] 게시글 전체 조회 오류 수정
  src/main/java/com/soda/article/domain/article/ArticleListViewResponse.java
  src/main/java/com/soda/article/repository/ArticleRepository.java
  src/main/java/com/soda/article/service/ArticleService.java
Labels: 🐞 Bugfix

#122 [Feature] 승인요청 조건 조회 및 페이지네이션 API 구현
  build.gradle
  src/main/java/com/soda/global/init/TestDataLoader.java
  src/main/java/com/soda/request/controller/RequestController.java
  src/main/java/com/soda/request/dto/GetRequestCondition.java
  src/main/java/com/soda/request/repository/RequestRepository.java
  src/main/java/com/soda/request/repository/RequestRepositoryCustom.java
  src/main/java/com/soda/request/repository/RequestRepositoryImpl.java
  src/main/java/com/soda/request/service/RequestService.java
  src/main/resources/application.yml
Labels: ✨ Feature

#132 [Fix] 승인요청 조회시 삭제된 데이터도 가져와지는 버그 수정
  src/main/java/com/soda/request/repository/RequestRepositoryImpl.java
Labels: 🐞 Bugfix

#134 [Fix] 게시글 링크/파일 삭제 API 오류 수정
  src/main/java/com/soda/article/domain/article/ArticleFileDTO.java
  src/main/java/com/soda/article/domain/article/ArticleLinkDTO.java
  src/main/java/com/soda/article/domain/article/ArticleModifyResponse.java
  src/main/java/com/soda/article/domain/article/ArticleViewResponse.java
Labels: 🐞 Bugfix

#142 [Feature] 프로젝트 생성 / 조회 기능 구현
  src/main/java/com/soda/SodaApplication.java
  src/main/java/com/soda/global/log/dataLog/aspect/EntityLogAspect.java
  src/main/java/com/soda/project/controller/ProjectController.java
  src/main/java/com/soda/project/controller/StageController.java
  src/main/java/com/soda/project/domain/ProjectCreateResponse.java
  src/main/java/com/soda/project/domain/ProjectListResponse.java
  src/main/java/com/soda/project/domain/ProjectResponse.java
  src/main/java/com/soda/project/domain/ProjectStatusUpdateRequest.java
  src/main/java/com/soda/project/dto/CompanyProjectDTO.java
  src/main/java/com/soda/project/dto/DevCompanyAssignmentRequest.java
  src/main/java/com/soda/project/dto/DevCompanyAssignmentResponse.java
  src/main/java/com/soda/project/dto/MemberProjectDTO.java
  src/main/java/com/soda/project/dto/ProjectCreateRequest.java
  src/main/java/com/soda/project/dto/ProjectCreateResponse.java
  src/main/java/com/soda/project/dto/ProjectDTO.java
  src/main/java/com/soda/project/dto/ProjectListResponse.java
  src/main/java/com/soda/project/dto/stage/StageCreateRequest.java
  src/main/java/com/soda/project/dto/stage/StageMoveRequest.java
  src/main/java/com/soda/project/dto/stage/StageReadResponse.java
  src/main/java/com/soda/project/dto/stage/StageResponse.java
  src/main/java/com/soda/project/dto/stage/StageUpdateRequest.java
  src/main/java/com/soda/project/error/ProjectErrorCode.java
  src/main/java/com/soda/project/repository/CompanyProjectRepository.java
  src/main/java/com/soda/project/repository/MemberProjectRepository.java
  src/main/java/com/soda/project/repository/ProjectRepository.java
  src/main/java/com/soda/project/service/CompanyProjectService.java
  src/main/java/com/soda/project/service/MemberProjectService.java
  src/main/java/com/soda/project/service/ProjectService.java
  src/main/java/com/soda/project/service/StageService.java
Labels: ✨ Feature

#144 [Fix] 삭제된 승인권자가 조회되는 버그 해결
  src/main/java/com/soda/request/dto/request/RequestDTO.java
Labels: 🐞 Bugfix

#146 [CICD & FIX] cors에 프론트 url 오타 정정(www를 빠뜨림)
  src/main/java/com/soda/global/security/config/SecurityConfig.java
Labels: 🐞 Bugfix, 🤖 CI/CD

#147 [Feature] 프로젝트 CRUD 일부 구현
  src/main/java/com/soda/member/enums/CompanyProjectRole.java
  src/main/java/com/soda/project/controller/ProjectController.java
  src/main/java/com/soda/project/dto/ProjectCompanyAddRequest.java
  src/main/java/com/soda/project/dto/ProjectCompanyAddResponse.java
  src/main/java/com/soda/project/dto/ProjectInfoUpdateRequest.java
  src/main/java/com/soda/project/dto/ProjectInfoUpdateResponse.java
  src/main/java/com/soda/project/dto/ProjectStatusUpdateRequest.java
  src/main/java/com/soda/project/dto/ProjectStatusUpdateResponse.java
  src/main/java/com/soda/project/dto/ProjectViewResponse.java
  src/main/java/com/soda/project/entity/Project.java
  src/main/java/com/soda/project/error/ProjectErrorCode.java
  src/main/java/com/soda/project/service/CompanyProjectService.java
  src/main/java/com/soda/project/service/ProjectService.java
Labels: ✨ Feature

#148 [Feature] 프로젝트 참여 회사/멤버 관리 기능 구현
  src/main/java/com/soda/member/enums/CompanyProjectRole.java
  src/main/java/com/soda/project/controller/ProjectController.java
  src/main/java/com/soda/project/dto/ProjectMemberAddRequest.java
  src/main/java/com/soda/project/dto/ProjectMemberAddResponse.java
  src/main/java/com/soda/project/error/ProjectErrorCode.java
  src/main/java/com/soda/project/repository/CompanyProjectRepository.java
  src/main/java/com/soda/project/repository/MemberProjectRepository.java
  src/main/java/com/soda/project/service/CompanyProjectService.java
  src/main/java/com/soda/project/service/MemberProjectService.java
  src/main/java/com/soda/project/service/ProjectService.java
Labels: ✨ Feature

#152 [Fix] 프로젝트 생성/개발사 추가 시, 회사와 멤버를 중복 추가 시 생기는 오류 해결
  src/main/java/com/soda/project/dto/CompanyAssignment.java
  src/main/java/com/soda/project/dto/DevCompanyAssignmentRequest.java
  src/main/java/com/soda/project/dto/DevCompanyAssignmentResponse.java
  src/main/java/com/soda/project/dto/ProjectCreateRequest.java
  src/main/java/com/soda/project/dto/ProjectCreateResponse.java
  src/main/java/com/soda/project/repository/MemberProjectRepository.java
  src/main/java/com/soda/project/service/MemberProjectService.java
  src/main/java/com/soda/project/service/ProjectService.java
Labels: 🐞 Bugfix

#154 [Feature] 프로젝트에 속한 멤버들 조회 기능
  src/main/java/com/soda/project/controller/ProjectController.java
  src/main/java/com/soda/project/dto/ProjectMemberResponse.java
  src/main/java/com/soda/project/repository/CompanyProjectRepository.java
  src/main/java/com/soda/project/repository/MemberProjectRepository.java
  src/main/java/com/soda/project/service/CompanyProjectService.java
  src/main/java/com/soda/project/service/MemberProjectService.java
  src/main/java/com/soda/project/service/ProjectService.java
Labels: ✨ Feature

#156 [Refactor] 프로젝트에 속한 멤버들 조회 기능 query 부분 리팩토링
  src/main/java/com/soda/global/config/QueryDslConfig.java
  src/main/java/com/soda/project/controller/ProjectController.java
  src/main/java/com/soda/project/dto/ProjectMemberSearchCondition.java
  src/main/java/com/soda/project/repository/MemberProjectRepository.java
  src/main/java/com/soda/project/repository/MemberProjectRepositoryCustom.java
  src/main/java/com/soda/project/repository/MemberProjectRepositoryImpl.java
  src/main/java/com/soda/project/service/MemberProjectService.java
  src/main/java/com/soda/project/service/ProjectService.java
Labels: 🔧 Refactor

#158 [Feature] 사용자 대시보드 - 최근 게시글 3개 조회 기능
  src/main/java/com/soda/article/controller/ArticleController.java
  src/main/java/com/soda/article/controller/CommentController.java
  src/main/java/com/soda/article/dto/article/ArticleCreateRequest.java
  src/main/java/com/soda/article/dto/article/ArticleCreateResponse.java
  src/main/java/com/soda/article/dto/article/ArticleDTO.java
  src/main/java/com/soda/article/dto/article/ArticleFileDTO.java
  src/main/java/com/soda/article/dto/article/ArticleLinkDTO.java
  src/main/java/com/soda/article/dto/article/ArticleListViewResponse.java
  src/main/java/com/soda/article/dto/article/ArticleModifyRequest.java
  src/main/java/com/soda/article/dto/article/ArticleModifyResponse.java
  src/main/java/com/soda/article/dto/article/ArticleViewResponse.java
  src/main/java/com/soda/article/dto/article/RecentArticleResponse.java
  src/main/java/com/soda/article/dto/comment/CommentCreateRequest.java
  src/main/java/com/soda/article/dto/comment/CommentCreateResponse.java
  src/main/java/com/soda/article/dto/comment/CommentDTO.java
  src/main/java/com/soda/article/dto/comment/CommentUpdateRequest.java
  src/main/java/com/soda/article/dto/comment/CommentUpdateResponse.java
  src/main/java/com/soda/article/repository/ArticleRepository.java
  src/main/java/com/soda/article/service/ArticleFileService.java
  src/main/java/com/soda/article/service/ArticleLinkService.java
  src/main/java/com/soda/article/service/ArticleService.java
  src/main/java/com/soda/article/service/CommentService.java
  src/main/java/com/soda/global/log/dataLog/aspect/EntityLogAspect.java
  src/main/java/com/soda/project/repository/MemberProjectRepository.java
  src/main/java/com/soda/project/repository/StageRepository.java
  src/main/java/com/soda/project/service/MemberProjectService.java
  src/main/java/com/soda/project/service/StageService.java
Labels: ✨ Feature

#162 [Fix] 프로젝트에 회사 추가 시 기존 사용자 권한 수정 안되는 버그 수정
  src/main/java/com/soda/project/entity/MemberProject.java
  src/main/java/com/soda/project/repository/MemberProjectRepository.java
  src/main/java/com/soda/project/service/MemberProjectService.java
Labels: 🐞 Bugfix

#186 [Fix] 데이터 로그 조회 API 호출 시 페이지네이션의 totalPage가 1로만 반환되는 버그 수정
  src/main/java/com/soda/global/log/dataLog/domain/DataLogCustomRepositoryImpl.java
Labels: 🐞 Bugfix

#189 [Feature] 게시글 생성 시 투표 기능 추가
  src/main/java/com/soda/article/controller/ArticleController.java
  src/main/java/com/soda/article/dto/article/VoteCreateRequest.java
  src/main/java/com/soda/article/dto/article/VoteCreateResponse.java
  src/main/java/com/soda/article/entity/Article.java
  src/main/java/com/soda/article/entity/Vote.java
  src/main/java/com/soda/article/entity/VoteAnswer.java
  src/main/java/com/soda/article/entity/VoteAnswerItem.java
  src/main/java/com/soda/article/entity/VoteItem.java
  src/main/java/com/soda/article/error/ArticleErrorCode.java
  src/main/java/com/soda/article/error/CommentErrorCode.java
  src/main/java/com/soda/article/error/VoteErrorCode.java
  src/main/java/com/soda/article/repository/VoteItemRepository.java
  src/main/java/com/soda/article/repository/VoteRepository.java
  src/main/java/com/soda/article/service/ArticleService.java
  src/main/java/com/soda/article/service/VoteItemService.java
  src/main/java/com/soda/article/service/VoteService.java
Labels: ✨ Feature

#195 [Fix] 사용자가 참여 중인 프로젝트 목록이 없으면 경우 오류 수정
  src/main/java/com/soda/project/service/ProjectService.java
Labels: 🐞 Bugfix

#194 [Refactor] Request 수정 요청시 로깅에서 500에러 뜨는 버그 해결
  src/main/java/com/soda/global/log/dataLog/aspect/EntityLogAspect.java
  src/main/java/com/soda/request/dto/request/ReRequestCreateResponse.java
  src/main/java/com/soda/request/dto/request/RequestCreateResponse.java
  src/main/java/com/soda/request/dto/request/RequestDTO.java
  src/main/java/com/soda/request/dto/request/RequestDeleteResponse.java
  src/main/java/com/soda/request/dto/request/RequestUpdateResponse.java
Labels: 🐞 Bugfix

#196 [Feature] 사용자의 회사가 참여 중인 프로젝트 목록 조회 기능
  src/main/java/com/soda/project/controller/ProjectController.java
  src/main/java/com/soda/project/dto/MyProjectListResponse.java
  src/main/java/com/soda/project/repository/ProjectRepository.java
  src/main/java/com/soda/project/repository/ProjectRepositoryCustom.java
  src/main/java/com/soda/project/repository/ProjectRepositoryImpl.java
  src/main/java/com/soda/project/service/ProjectService.java
Labels: ✨ Feature

#197 [Feature] 프로젝트 상세 조회 시 유효성 검사 추가
  src/main/java/com/soda/project/service/ProjectService.java
Labels: ✨ Feature

#203 [Feature] 게시글 투표 기본 정보 조회 기능
  src/main/java/com/soda/article/controller/ArticleController.java
  src/main/java/com/soda/article/dto/article/VoteViewResponse.java
  src/main/java/com/soda/article/service/ArticleService.java
Labels: ✨ Feature

#200 [Feature] Request 작성자, 승인권자, 프로젝트(선택)을 바탕으로 조회하는 API 구현
  src/main/java/com/soda/request/controller/RequestController.java
  src/main/java/com/soda/request/dto/request/GetMemberRequestCondition.java
  src/main/java/com/soda/request/repository/RequestRepositoryCustom.java
  src/main/java/com/soda/request/repository/RequestRepositoryImpl.java
  src/main/java/com/soda/request/service/RequestService.java
Labels: ✨ Feature

#202 [Feature] 특정 프로젝트의 승인요청 조회 API에 검색조건 추가
  src/main/java/com/soda/request/dto/GetRequestCondition.java
  src/main/java/com/soda/request/repository/RequestRepositoryImpl.java
Labels: ✨ Feature

#204 [Feature] 데이터 로그 키워드 검색 기능 구현
  src/main/java/com/soda/global/log/dataLog/aspect/EntityLogAspect.java
  src/main/java/com/soda/global/log/dataLog/domain/DataLog.java
  src/main/java/com/soda/global/log/dataLog/domain/DataLogCustomRepositoryImpl.java
  src/main/java/com/soda/global/log/dataLog/dto/DataLogSearchRequest.java
Labels: ✨ Feature

#206 [Fix] 특정 프로젝트 승인요청 전체 조회시 projectId 조건 추가
  src/main/java/com/soda/request/controller/RequestController.java
  src/main/java/com/soda/request/repository/RequestRepositoryCustom.java
  src/main/java/com/soda/request/repository/RequestRepositoryImpl.java
  src/main/java/com/soda/request/service/RequestService.java
Labels: 🐞 Bugfix

#207 [Refactor] 1MB 이상의 파일도 저장할 수 있게 수정
  src/main/resources/application.yml
Labels: 🔧 Refactor

#208 [Feature] 투표하기 기능 추가
  src/main/java/com/soda/article/controller/ArticleController.java
  src/main/java/com/soda/article/dto/article/VoteSubmitRequest.java
  src/main/java/com/soda/article/dto/article/VoteSubmitResponse.java
  src/main/java/com/soda/article/error/VoteErrorCode.java
  src/main/java/com/soda/article/repository/ArticleRepositoryCustom.java
  src/main/java/com/soda/article/repository/ArticleRepositoryImpl.java
  src/main/java/com/soda/article/repository/VoteAnswerItemRepository.java
  src/main/java/com/soda/article/repository/VoteAnswerRepository.java
  src/main/java/com/soda/article/repository/VoteRepository.java
  src/main/java/com/soda/article/service/ArticleService.java
  src/main/java/com/soda/article/service/VoteAnswerItemService.java
  src/main/java/com/soda/article/service/VoteAnswerService.java
  src/main/java/com/soda/article/service/VoteItemService.java
  src/main/java/com/soda/article/service/VoteService.java
  src/main/java/com/soda/member/repository/MemberRepository.java
  src/main/java/com/soda/member/service/MemberService.java
Labels: ✨ Feature

#210 [Feature] 게시글 투표 결과 조회 기능
  src/main/java/com/soda/article/controller/ArticleController.java
  src/main/java/com/soda/article/dto/article/VoteResultResponse.java
  src/main/java/com/soda/article/repository/VoteAnswerItemRepository.java
  src/main/java/com/soda/article/repository/VoteAnswerItemRepositoryCustom.java
  src/main/java/com/soda/article/repository/VoteAnswerItemRepositoryImpl.java
  src/main/java/com/soda/article/repository/VoteAnswerRepository.java
  src/main/java/com/soda/article/service/ArticleService.java
  src/main/java/com/soda/article/service/VoteAnswerItemService.java
  src/main/java/com/soda/article/service/VoteAnswerService.java
  src/main/java/com/soda/article/service/VoteService.java
Labels: ✨ Feature

#212 [Feature] 프로젝트 제목으로 검색 기능 추가
  src/main/java/com/soda/project/controller/ProjectController.java
  src/main/java/com/soda/project/dto/ProjectSearchCondition.java
  src/main/java/com/soda/project/repository/ProjectRepositoryCustom.java
  src/main/java/com/soda/project/repository/ProjectRepositoryImpl.java
  src/main/java/com/soda/project/service/ProjectService.java
Labels: ✨ Feature

#213 [Feature] 게시글 검색 기능
  src/main/java/com/soda/article/controller/ArticleController.java
  src/main/java/com/soda/article/dto/article/ArticleSearchCondition.java
  src/main/java/com/soda/article/repository/ArticleRepositoryCustom.java
  src/main/java/com/soda/article/repository/ArticleRepositoryImpl.java
  src/main/java/com/soda/article/service/ArticleService.java
Labels: ✨ Feature

#214 [Feature] 파일 저장 책임을 FE에 위임하고 서버에서는 S3 Presigned URL 생성, 발급과 DB에 파일 URL 저장하는 행동을 하도록 수정
  build.gradle
  src/main/java/com/soda/article/controller/ArticleController.java
  src/main/java/com/soda/article/strategy/ArticleFileStrategy.java
  src/main/java/com/soda/common/file/dto/ConfirmedFile.java
  src/main/java/com/soda/common/file/dto/FileConfirmResponse.java
  src/main/java/com/soda/common/file/dto/FileUploadRequest.java
  src/main/java/com/soda/common/file/dto/PresignedUploadResponse.java
  src/main/java/com/soda/common/file/service/FileService.java
  src/main/java/com/soda/common/file/service/S3Service.java
  src/main/java/com/soda/common/file/strategy/FileStrategy.java
  src/main/java/com/soda/global/config/AWSConfig.java
  src/main/java/com/soda/global/config/AWSS3Config.java
  src/main/java/com/soda/global/log/dataLog/aspect/EntityLogAspect.java
  src/main/java/com/soda/request/controller/RequestController.java
  src/main/java/com/soda/request/controller/ResponseController.java
  src/main/java/com/soda/request/strategy/RequestFileStrategy.java
  src/main/java/com/soda/request/strategy/ResponseFileStrategy.java
Labels: ✨ Feature

#217 [Feat] 멤버id 기반 승인요청 조회시 projectId도 반환되도록 수정
  src/main/java/com/soda/request/dto/request/RequestDTO.java
Labels: ✨ Feature

#226 [Feature] 특정 멤버 승인요청 조회 API 에서 키워드 기반 검색 기능 구현
  src/main/java/com/soda/request/dto/request/GetMemberRequestCondition.java
  src/main/java/com/soda/request/repository/RequestRepositoryImpl.java
Labels: ✨ Feature

#227 [Feature] SSE 구독 엔드포인트 구현
  src/main/java/com/soda/notice/controller/NoticeController.java
  src/main/resources/application.yml
Labels: ✨ Feature

#230 [Fix] 고객사/개발사 멤버 제대로 추가 안되는 버그 수정
  src/main/java/com/soda/project/error/ProjectErrorCode.java
  src/main/java/com/soda/project/repository/CompanyProjectRepository.java
  src/main/java/com/soda/project/service/CompanyProjectService.java
  src/main/java/com/soda/project/service/MemberProjectService.java
Labels: 🐞 Bugfix

#232 [Feature] 최근 활동이 많은 프로젝트 조회 API 개발
  src/main/java/com/soda/project/controller/ProjectController.java
  src/main/java/com/soda/project/dto/ProjectListResponse.java
  src/main/java/com/soda/project/repository/ProjectRepositoryCustom.java
  src/main/java/com/soda/project/repository/ProjectRepositoryImpl.java
  src/main/java/com/soda/project/service/ProjectService.java
Labels: ✨ Feature

#233 [Feature] 프로젝트 상태 진행중으로 변경 로직 추가
  src/main/java/com/soda/project/service/ProjectService.java
Labels: ✨ Feature

#229 [Feature] SseEmitter 관리 서비스 구현
  src/main/java/com/soda/notice/service/EmitterService.java
Labels: ✨ Feature

#236 [Feature] 시스템로깅시 파일로 먼저 로깅하고 이를 LogStash를 이용해 비동기적으로 mongoDB로 수집하도록 수정
  .gitignore
  build.gradle
  docker-compose.yml
  logstash/Dockerfile
  logstash/logstash.conf
  src/main/java/com/soda/global/log/systemLog/appender/MongoAppenderRegistrar.java
  src/main/java/com/soda/global/log/systemLog/appender/MongoDbLogAppender.java
  src/main/java/com/soda/global/log/systemLog/domain/LogRepository.java
  src/main/java/com/soda/global/log/systemLog/domain/SystemLog.java
  src/main/resources/logback-spring.xml
Labels: ✨ Feature

#237 [Fix] logstash.conf 환경변수 변경
  logstash/logstash.conf
Labels: 🐞 Bugfix

#238 [Fix] logstash.conf 환경변수에 쌍따옴표("") 추가
  logstash/logstash.conf
Labels: 🐞 Bugfix

#242 [Feature] 게시글 '답변완료'로 변경하는 기능
  src/main/java/com/soda/article/controller/ArticleController.java
  src/main/java/com/soda/article/dto/article/ArticleStatusUpdateRequest.java
  src/main/java/com/soda/article/dto/article/ArticleStatusUpdateResponse.java
  src/main/java/com/soda/article/entity/Article.java
  src/main/java/com/soda/article/service/ArticleService.java
Labels: ✨ Feature

#244 [Fix] 게시글 삭제 오류 해결
  src/main/java/com/soda/article/entity/Article.java
Labels: 🐞 Bugfix

#246 [Fix] 게시글 조회 시 게시글 상태 조회 안되는 오류 수정
  src/main/java/com/soda/article/dto/article/ArticleViewResponse.java
Labels: 🐞 Bugfix

#249 [Fix&Refact] 저장시각이 문자열로 저장되는 버그 해결, 필요없는 필드 삭제, INFO레벨 이상만 로깅되게 수정
  logstash/logstash.conf
  src/main/resources/logback-spring.xml
Labels: 🐞 Bugfix, 🔧 Refactor

#251 [Fix] 몽고DB에 중복로깅되는 버그 해결
  logstash/logstash.conf
Labels: 🐞 Bugfix

#253 [Feature] 로그 생성시간/로깅시간 구분하여 로깅
  logstash/logstash.conf
Labels: ✨ Feature

#247 [Feature] 회사 생성 추이 통계 조회 기능 구현
  src/main/java/com/soda/member/controller/CompanyController.java
  src/main/java/com/soda/member/dto/CompanyCreationStatRaw.java
  src/main/java/com/soda/member/dto/CompanyCreationTrend.java
  src/main/java/com/soda/member/dto/company/CompanyTrendSearchCondition.java
  src/main/java/com/soda/member/enums/StatisticsUnit.java
  src/main/java/com/soda/member/repository/CompanyRepository.java
  src/main/java/com/soda/member/repository/CompanyRepositoryCustom.java
  src/main/java/com/soda/member/repository/CompanyRepositoryImpl.java
  src/main/java/com/soda/member/service/CompanyService.java
Labels: ✨ Feature

#257 [Feature] 프로젝트 생성 통계 구현
  src/main/java/com/soda/SodaApplication.java
  src/main/java/com/soda/project/controller/ProjectController.java
  src/main/java/com/soda/project/dto/ProjectStatsCondition.java
  src/main/java/com/soda/project/dto/ProjectStatsResponse.java
  src/main/java/com/soda/project/event/ProjectCreatedEvent.java
  src/main/java/com/soda/project/event/ProjectEventListener.java
  src/main/java/com/soda/project/service/ProjectService.java
  src/main/java/com/soda/project/stats/entity/ProjectDailyStats.java
  src/main/java/com/soda/project/stats/repository/ProjectDailyStatsRepository.java
  src/main/java/com/soda/project/stats/repository/ProjectDailyStatsRepositoryCustom.java
  src/main/java/com/soda/project/stats/repository/ProjectDailyStatsRepositoryImpl.java
  src/main/java/com/soda/project/stats/service/ProjectStatsUpdateService.java
Labels: ✨ Feature

#260 [Fix] 프로젝트 생성을 하지 않는 경우 통계에 저장되지 않는 오류 해결
  src/main/java/com/soda/project/service/ProjectService.java
Labels: 🐞 Bugfix

#262 [Fix] 프로젝트에 멤버 추가 시 중복 저장 오류 해결
  src/main/java/com/soda/project/service/MemberProjectService.java
  src/main/java/com/soda/project/service/ProjectService.java
Labels: 🐞 Bugfix

#264 [Refactor] Request 페이지네이션 시 생성일 기준으로 정렬하되 재승인요청의 경우 부모요청 바로 아래에 순서가 위치하게 수정
  src/main/java/com/soda/request/repository/RequestRepositoryImpl.java
Labels: 🔧 Refactor

#266 [Feature] 게시글 목록 조회 시 PriorityType, ArticleStatus 필터링 기능 추가
  src/main/java/com/soda/article/dto/article/ArticleSearchCondition.java
  src/main/java/com/soda/article/repository/ArticleRepositoryImpl.java
Labels: ✨ Feature

#268 [Fix] 특정 멤버의 승인요청 조회할 때 승인요청이 속한 project의 isDeleted가 false인 데이터만 조회되게 수정
  src/main/java/com/soda/request/repository/RequestRepositoryImpl.java
Labels: 🐞 Bugfix

#272 [Feat] 응답시간 로깅 AOP 구현 및 logstash 응답시간 분기 처리
  logstash/logstash.conf
  src/main/java/com/soda/article/service/ArticleService.java
  src/main/java/com/soda/article/service/CommentService.java
  src/main/java/com/soda/global/log/data/annotation/LoggableEntityAction.java
  src/main/java/com/soda/global/log/data/aspect/EntityLogAspect.java
  src/main/java/com/soda/global/log/data/controller/DataLogController.java
  src/main/java/com/soda/global/log/data/domain/DataLog.java
  src/main/java/com/soda/global/log/data/domain/DataLogCustomRepository.java
  src/main/java/com/soda/global/log/data/domain/DataLogCustomRepositoryImpl.java
  src/main/java/com/soda/global/log/data/domain/DataLogRepository.java
  src/main/java/com/soda/global/log/data/dto/DataLogSearchRequest.java
  src/main/java/com/soda/global/log/data/dto/DataLogSearchResponse.java
  src/main/java/com/soda/global/log/data/service/DataLogService.java
  src/main/java/com/soda/global/log/responsetime/ControllerLoggingAspect.java
  src/main/java/com/soda/member/service/CompanyService.java
  src/main/java/com/soda/project/service/ProjectService.java
  src/main/java/com/soda/project/service/StageService.java
  src/main/java/com/soda/request/service/RequestService.java
  src/main/java/com/soda/request/service/ResponseService.java
Labels: ✨ Feature

#273 [Fix] 응답시간 로깅시 중괄호를 하나 더 넣어 응답시간이 부정확한 위치에 로깅되는 버그 해결
  src/main/java/com/soda/global/log/responsetime/ControllerLoggingAspect.java
Labels: 🐞 Bugfix
